apiVersion: v1
kind: Secret
metadata:
  name: montreal-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==
  Mongo_URL: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUB3ZWItZGI6MjcwMTcv
  JWT_SECRET: TW9udHJlYWw=
